export const CONSENT_DOCS = [
  {
    id: "hipaa",
    num: 1,
    icon: "🛡",
    title: "HIPAA Acknowledgment",
    subtitle: "Notice of Privacy Practices",
    short: [
      "Eden ABA Therapy may use and disclose PHI for treatment, payment, and healthcare operations.",
      "My child's health information may include medical, developmental, behavioral, treatment, insurance, billing, and service-related information.",
      "I have read and understand Eden ABA Therapy's Notice of Privacy Practices.",
    ],
    ack: "I acknowledge that I have received or been given access to Eden ABA Therapy's Notice of Privacy Practices.",
    items: [
      "Eden ABA Therapy may use and disclose protected health information (PHI) for treatment, payment, and healthcare operations as permitted or required by law.",
      "My child's protected health information may include medical, developmental, behavioral, treatment, insurance, billing, and service-related information.",
      "Eden ABA Therapy is required by law to protect the privacy and security of protected health information, follow the privacy practices described in its Notice of Privacy Practices, and notify me if a breach occurs that may compromise privacy or security.",
      "I understand that I can obtain a paper copy of the Notice of Privacy Practices at any time by asking a staff member or contacting the office.",
      "I understand that signing this acknowledgment does not authorize the release of information beyond what is permitted by law or described in the Notice of Privacy Practices.",
    ],
  },
  {
    id: "abaConsent",
    num: 2,
    icon: "🤲",
    title: "Consent for ABA Services",
    subtitle: "Authorization for ABA Assessment and Therapy Services",
    short: [
      "I give consent for Eden ABA Therapy to provide ABA assessment and therapy services for my child.",
      "Services may include intake, assessment, treatment planning, direct ABA therapy, caregiver training, supervision, and care coordination.",
      "I understand services are individualized and outcomes may vary.",
    ],
    ack: "I give consent for Eden ABA Therapy to provide ABA assessment and therapy services for my child.",
    items: [
      "I give permission for Eden ABA Therapy to provide Applied Behavior Analysis (ABA) services for my child.",
      "Services may include intake review, parent interview, observation, assessment, behavior assessment, skill assessment, treatment planning, caregiver training, direct ABA therapy, supervision, progress monitoring, and coordination of care.",
      "I understand that ABA services may be provided by qualified staff under appropriate supervision, including BCBAs, BCaBAs, Registered Behavior Technicians, behavior technicians, trainees, or other authorized clinical team members.",
      "I understand that ABA therapy is individualized and may include teaching communication, social, adaptive, play, safety, behavior reduction, and daily living skills.",
      "I understand that treatment recommendations may change based on assessment results, insurance authorization, clinical need, family availability, and progress.",
      "I understand that participation from parents or guardians is important for treatment success.",
      "I understand that I may ask questions about services at any time.",
    ],
  },
  {
    id: "guardianAgreement",
    num: 3,
    icon: "👥",
    title: "Parent / Guardian Agreement",
    subtitle: "Family Participation and Service Agreement",
    short: [
      "I have read and agree to the Parent / Guardian Agreement.",
      "I understand my responsibilities and Eden ABA Therapy's policies as outlined in this agreement.",
    ],
    ack: "I have read and agree to the terms of this Parent / Guardian Agreement.",
    items: [
      "Eden ABA Therapy will provide services based on clinical recommendations, availability, insurance authorization, and family participation.",
      "I agree to provide accurate and complete information regarding my child's medical history, diagnosis, insurance, emergency contacts, medications, allergies, behavioral concerns, family goals, and other information relevant to services.",
      "I agree to notify Eden ABA Therapy of any changes in insurance, address, phone number, medical condition, medications, custody arrangements, emergency contacts, school placement, or service needs.",
      "I understand that parent or caregiver involvement may be required, including participation in parent training, treatment planning, progress updates, and supporting skill generalization at home and in the community.",
      "I agree to treat Eden ABA Therapy staff with respect and maintain professional, courteous communication at all times.",
      "I understand that services may be paused, rescheduled, or discontinued if required documentation is missing, authorizations expire, safety concerns arise, or policies are not followed.",
      "I understand that ABA services are individualized and outcomes vary based on each child's skills, needs, consistency, and family participation.",
      "I understand that fees, copays, deductibles, and non-covered services are my responsibility as outlined in the financial policy.",
      "I understand that Eden ABA Therapy reserves the right to update policies and procedures as needed and will communicate any changes to families.",
    ],
  },
  {
    id: "roi",
    num: 4,
    icon: "📄",
    title: "Release of Information Authorization",
    subtitle: "Authorization to Request, Receive, and Exchange Information",
    short: [
      "I authorize Eden ABA Therapy to request, receive, share, and exchange information necessary for my child's care and services.",
      "This may include providers, schools, insurers, and other relevant organizations.",
      "This authorization remains in effect for 12 months unless revoked earlier in writing.",
    ],
    ack: "I authorize Eden ABA Therapy to exchange information as needed for my child's care and services.",
    items: [
      "I authorize Eden ABA Therapy to request, receive, share, and exchange information as needed for my child's care, treatment planning, insurance authorization, coordination of services, and continuity of care.",
      "Information may be shared with physicians or pediatricians, psychologists or diagnostic providers, schools, teachers, IEP teams, educational staff, speech therapists, occupational therapists, physical therapists, insurance companies, case managers, other healthcare or service providers, and government agencies when required by law or with permission.",
      "Information may include diagnosis, treatment recommendations, assessment results, progress summaries, behavior plans, therapy notes, attendance information, insurance information, medical records, school reports, IEPs, evaluation reports, referral documents, billing information, and any other information relevant to my child's care and services.",
      "This authorization is voluntary. I may refuse to sign this authorization; however, refusal may affect Eden ABA Therapy's ability to obtain or share information necessary for my child's care.",
      "I may revoke this authorization at any time by providing written notice to Eden ABA Therapy.",
      "Revocation will not apply to information that has already been released based on this authorization.",
      "This authorization will remain in effect for 12 months from the date signed below, unless revoked earlier in writing.",
    ],
  },
  {
    id: "pickup",
    num: 5,
    icon: "🔐",
    title: "Authorization for Pick-Up & Release",
    subtitle: "Child Safety and Authorized Release",
    short: [
      "I authorize Eden ABA Therapy to release my child only to authorized individuals.",
      "Authorized individuals may be required to show valid photo identification.",
      "I agree to provide updates if authorized pick-up individuals change.",
    ],
    ack: "I authorize Eden ABA Therapy to release my child only to approved individuals listed below.",
    items: [
      "I authorize Eden ABA Therapy to release my child only to the parent, legal guardian, or individuals listed as authorized pick-up persons.",
      "Authorized individuals may be required to show valid photo identification before my child is released.",
      "I agree to provide Eden ABA Therapy with updated information if authorized pick-up persons change at any time.",
      "If there are custody orders, court restrictions, protective orders, or individuals who are not permitted to pick up my child, I must provide written notice and supporting legal documentation to Eden ABA Therapy.",
      "I understand that Eden ABA Therapy may refuse release of my child if staff cannot verify the identity or authorization of the person attempting to pick up my child.",
      "I agree to notify Eden ABA Therapy immediately if there is any change in custody, guardianship, or any legal restriction that may affect pick-up or release.",
    ],
    extra: "pickup",
  },
  {
    id: "telehealth",
    num: 6,
    icon: "💻",
    title: "Telehealth Consent (If Applicable)",
    subtitle: "Consent for Telehealth Services",
    short: [
      "I consent to participate in telehealth services when appropriate and available.",
      "I understand the benefits, risks, and limitations of telehealth.",
      "I understand I may withdraw consent at any time.",
    ],
    ack: "I consent to telehealth services when clinically appropriate and approved by Eden ABA Therapy.",
    items: [
      "I consent to participate in telehealth services with Eden ABA Therapy when clinically appropriate and approved by the clinical team or funding source.",
      "Telehealth may be used for parent training, caregiver consultation, supervision, assessment follow-up, care coordination, or other approved services.",
      "I understand that telehealth services may involve electronic communication and that Eden ABA Therapy will use reasonable safeguards to protect privacy.",
      "I understand that I am responsible for having the necessary technology and internet connection to participate in telehealth sessions.",
      "I understand that I may withdraw consent for telehealth at any time by providing a written request. Withdrawing consent may impact service delivery and scheduling.",
    ],
  },
  {
    id: "attendance",
    num: 7,
    icon: "📅",
    title: "Attendance Policy Acknowledgment",
    subtitle: "Our Commitment to Consistent Care",
    short: [
      "I have read and understand Eden ABA Therapy's Attendance Policy.",
      "I understand that missed or late sessions may impact my child's progress.",
      "I agree to notify Eden ABA Therapy as early as possible regarding absences.",
    ],
    ack: "I have read and understand Eden ABA Therapy's Attendance Policy and agree to follow it.",
    items: [
      "Consistent attendance is essential for my child's progress in ABA therapy.",
      "I agree to make reasonable efforts to ensure my child attends all scheduled ABA therapy sessions.",
      "I understand that I must notify Eden ABA Therapy as soon as possible if my child is unable to attend a scheduled session.",
      "I understand that repeated absences, late arrivals, early pickups, or missed sessions may impact my child's progress and interfere with treatment goals, staff scheduling, and insurance authorization.",
      "I understand that sessions canceled with insufficient notice may be considered billable as outlined in our cancellation policy.",
    ],
  },
  {
    id: "cancellation",
    num: 8,
    icon: "🕘",
    title: "Cancellation Policy Acknowledgment",
    subtitle: "Our Commitment to Respectful Scheduling",
    short: [
      "I have read and understand Eden ABA Therapy's Cancellation Policy.",
      "I understand advance notice is required for cancellations.",
      "I understand late cancellations or no-shows may be billable.",
    ],
    ack: "I have read and understand Eden ABA Therapy's Cancellation Policy and agree to follow it.",
    items: [
      "I understand that Eden ABA Therapy requires advance notice when a scheduled session must be canceled.",
      "I agree to notify Eden ABA Therapy as early as possible if my child cannot attend a scheduled session.",
      "I understand that frequent cancellations or late notices may impact my child's progress, staff scheduling, service availability, and insurance authorization.",
      "I understand that Eden ABA Therapy may request a meeting with our family if cancellations become frequent or interfere with treatment.",
      "I understand that sessions may be rescheduled when possible, but makeup sessions are not always guaranteed.",
      "I understand that cancellations with less than the required notice may be considered billable as outlined below.",
      "I understand that Eden ABA Therapy may update cancellation procedures as needed and will communicate any changes to families.",
      "I understand that I am responsible for reviewing the latest cancellation policy and contacting the office if I have any questions.",
    ],
  },
  {
    id: "custody",
    num: 9,
    icon: "⚖️",
    title: "Custody & Legal Authority",
    subtitle: "Legal Decision-Making and Court Orders",
    short: [
      "I confirm that I have legal authority to make decisions for my child.",
      "I will provide documentation if requested.",
      "I will inform Eden ABA Therapy immediately if there are any changes.",
    ],
    ack: "I confirm I have legal authority to make decisions for my child.",
    items: [
      "This information helps us ensure we are following legal requirements and can communicate effectively with the appropriate individuals regarding your child's care.",
      "Both parents or guardians must provide accurate custody and legal authority information.",
      "If one parent or guardian has sole legal custody, legal documentation may be required.",
      "Court orders, custody agreements, protective orders, or restrictions must be disclosed and uploaded when applicable.",
      "I confirm that the information provided is accurate and complete to the best of my knowledge.",
      "I understand that I must notify Eden ABA Therapy immediately if there are any changes.",
    ],
    extra: "custody",
  },
  {
    id: "safety",
    num: 10,
    icon: "🛡️",
    title: "Safety & Incident Acknowledgment",
    subtitle: "Safety Considerations and Incident Communication",
    short: [
      "I understand Eden ABA Therapy follows safety procedures to protect all clients.",
      "I agree to inform the team of any safety concerns, medical conditions, or changes.",
      "I understand incidents will be communicated and documented as required.",
    ],
    ack: "I have read and understand Eden ABA Therapy's Safety & Incident Policies and agree to follow them.",
    items: [
      "Your child's safety and well-being are our top priority.",
      "Eden ABA Therapy is committed to providing a safe, supportive, and respectful environment for your child.",
      "Our staff are trained in de-escalation techniques, safety protocols, and incident prevention.",
      "If an incident occurs, Eden ABA Therapy will ensure immediate safety of your child and others, provide appropriate support and intervention, document the incident in detail, communicate with you promptly, follow required reporting laws and regulations, review the incident to help prevent future occurrences, and maintain confidentiality of incident information.",
      "I understand that ABA therapy may involve challenging behaviors such as aggression, self-injury, elopement, property destruction, or other behaviors that may pose a risk to my child or others.",
      "I acknowledge that Eden ABA Therapy will use appropriate safety and de-escalation strategies to protect my child and others.",
      "I agree to cooperate with all safety procedures and follow the guidance provided by the therapy team.",
      "I understand that if my child poses an immediate risk of harm to self or others, appropriate protective actions may be taken, which may include emergency intervention.",
      "I will inform Eden ABA Therapy of any changes in my child's medical, behavioral, or safety-related needs. I understand that concerns about safety or incidents will be communicated with me promptly.",
    ],
    extra: "safety",
  },
];

export function getConsentAckFields() {
  return CONSENT_DOCS.map((c) => ({
    name: `${c.id}Ack`,
    type: "consent-ack",
    required: true,
  }));
}
